name: MUSTAFA
favicon: null
layout_spectrum: 0.5924169409554452
typography_spectrum: 0.11624588281847537
title: PORTFOLIO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
